# -*- coding: utf-8 -*-
"""classify csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGiIQFti9Cslg7Jo_RIwtbImC5H9Yp8O
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

dataa = pd.read_csv('/content/drive/MyDrive/Final Year Design Project/Survey and collected data/MindSeer_Data_Collection (Responses) - Form Responses 1.csv')
data=np.array(dataa)

# print(data[0][4][0])
row,col=data.shape
Class=[]
# data = np.insert(data, col, 0, axis=1)
# print(data)
for i in range(row):
  dif=[7,11,15,19]
  score =0
  l=0
  for j in range(4,25):
    if l<4 and j == dif[l]:
      if(data[i][j][0])=='R':
        score+=3
      elif(data[i][j][0])=='S':
        score+=2
      elif(data[i][j][0])=='O':
        score+=1
      elif(data[i][j][0])=='M':
        score+=0
      l=l+1
    else:
      if(data[i][j][0])=='R':
        score+=0
      elif(data[i][j][0])=='S':
        score+=1
      elif(data[i][j][0])=='O':
        score+=2
      elif(data[i][j][0])=='M':
        score+=3

  if(score < 24):
    Class.append(0)
  else:
    # data = np.insert(data, 25, 1, axis=1)
    Class.append(1)
dataa['Class']=Class
print(np.array(dataa))
# print(data)

dataa.to_csv('data.csv')